# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4
  deadline: 1m
  tests: false
  modules-download-mode: vendor
  timeout: 5m
  skip-dirs:
    - test

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - goerr113
    - ireturn
    - maintidx
    - varnamelen

linters-settings:
  errcheck:
    exclude: .errcheck_excludes
  lll:
    line-length: 120
  funlen:
    lines: 70
    statements: 40